import Placeholder from '../assets/placeholder-image.jpg';

const dummyJobs = [
  {
    id: 1,
    title: 'Student Helper for EDC Thailand 2026 Concert',
    pay: '800/day',
    date: 'Jan 15-18, 2026',
    location: 'Rhythm Park, Cherngtalay, Phuket',
    hours: '08:00-18:00 (Jan 15), 12:00-01:00 (Jan 16-18)',
    isOpen: true,
    type: 'external',
    image: 'https://d3vhc53cl8e8km.cloudfront.net/hello-staging/wp-content/uploads/sites/124/2024/07/17180013/edth_2024_mk_an_fest_site_dh_1200x630_r01.jpg',
    capacity: 300,
    applicants: 269,
    postedBy: 'Student Development and Alumni Relations, PSU Phuket',
    postedDate: '2/2568',
    description: 'Recruitment for student helpers for the EDC Thailand 2026 concert (English communication skills required) during January 15-18, 2026 at Rhythm Park, Cherngtalay, Phuket.',
    schedule: [
      'Jan 15: Pre-Pick up Wristbands at Central Phuket (26 people) 08:00-18:00',
      'Jan 15: Pre-Pick up Wristbands at Porto de Phuket (27 people) 08:00-18:00',
      'Jan 16: Assigned duties at concert venue (272 people) 12:00-01:00',
      'Jan 17: Assigned duties at concert venue (226 people) 12:00-01:00',
      'Jan 18: Assigned duties at concert venue (226 people) 12:00-01:00',
    ],
    lineGroupUrl: '#',
  },
  {
    id: 2,
    title: 'Election Committee Staff at Ratsada Subdistrict',
    pay: '1,200',
    date: 'Feb 7-8, 2026',
    location: 'Ratsada Subdistrict, Phuket',
    hours: '08:00-17:00',
    isOpen: true,
    type: 'external',
    image: Placeholder,
    capacity: 50,
    applicants: 30,
    postedBy: 'Student Development and Alumni Relations, PSU Phuket',
    postedDate: '2/2568',
    description: 'Recruitment for election committee staff at Ratsada Subdistrict polling stations.',
    schedule: [
      'Feb 7: Setup and preparation 08:00-17:00',
      'Feb 8: Election day duties 08:00-17:00',
    ],
    lineGroupUrl: '#',
  },
  {
    id: 3,
    title: 'Equipment Installation Staff (Male Students Only)',
    pay: '3,000',
    date: 'Dec 28-31, 2025',
    location: 'Phuket Andaman Place',
    hours: '08:00-18:00',
    isOpen: false,
    type: 'external',
    image: Placeholder,
    capacity: 10,
    applicants: 10,
    postedBy: 'Student Development and Alumni Relations, PSU Phuket',
    postedDate: '1/2568',
    description: 'Recruitment for 10 male students for equipment installation work at Phuket Andaman Place.',
    schedule: [
      'Dec 28-31: Equipment installation duties 08:00-18:00',
    ],
    lineGroupUrl: '#',
  },
  {
    id: 4,
    title: 'English and Chinese Language Experience Activity',
    pay: '300/day',
    date: 'Dec 13, 27, 2025',
    location: 'PSU Phuket',
    hours: '09:00-16:00',
    isOpen: false,
    type: 'internal',
    image: Placeholder,
    capacity: 20,
    applicants: 20,
    postedBy: 'Student Development and Alumni Relations, PSU Phuket',
    postedDate: '1/2568',
    description: 'Activity to enhance English and Chinese language experience for PSU Phuket students.',
    schedule: [
      'Dec 13: Language activity session 09:00-16:00',
      'Dec 27: Language activity session 09:00-16:00',
    ],
    lineGroupUrl: '#',
  },
];

export default dummyJobs;