# Generated by Django 5.2.13 on 2026-04-30 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='jobs.application'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='grooming_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='punctuality_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='quality_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='responsibility_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='result_status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10),
        ),
    ]
